[general]
FLASK_SECRET_KEY = "your_flask_secret_key_here"

[firebase]
apiKey = "your_api_key_here"
authDomain = "your_auth_domain_here"
databaseURL = "your_database_url_here"
projectId = "your_project_id_here"
storageBucket = "your_storage_bucket_here"
messagingSenderId = "your_messaging_sender_id_here"
appId = "your_app_id_here"
